### ISSUE TITLE
Clarification requested

### ISSUE THREAD

**Issue by remarcmij** [PRB0t/PRB0t#13]
It is not entire clear to me in which scenarios and for whom this would be useful. Is it for use within HYF, or is it a general tool? Could you perhaps elaborate and provide the steps for one or two scenarios (in the README) where this would be an attractive alternative over doing pull requests in the traditional manner? The example with curl is good for showing the API but IMHO lacks the practicality of a real-world scenario.

**Comment by M3kH** [comment]
@remarcmij this is just a tool, not related with HYF.

There is couple of scenarios where you can use it.
For instance we could build an Editor on top that First fetches files from a Repository (with GitHub Api) and then allows to makes the edit and create a PR.

Eventually the editor could be embed with a script and you could have a link like, `Edit this content` to allow contributions from visitors of your website (if for instance you have the content in a GitHub repository).

Although there isn't an application that uses this API, due that has just being release; the only responsibility of the API is just what testable with the CURL example provided; thats why I think the current Readme is good enough.
