### ISSUE TITLE
Add an open source licence

### ISSUE THREAD

**Issue by smellems** [PRB0t/PRB0t#53]
Could you add an open source licence to this project?  I think it will help to get others to contribute.

MIT would be good!

**Comment by smellems** [comment]
Found this
https://github.com/PRB0t/PRB0t/blob/e82c87dcc8f93a58e9b09cb6782a46bdac2c2ef7/package.json#L27

But it would be good to have a LICENSE file also

**Comment by M3kH** [comment]
Thanks @smellems for the issue 🙏
This was a big missing here.

I add `MIT` license to the project.
Hope now is fine.
